db:
  image: "klaemo/couchdb:latest"
  ports:
    - "5984:5984"
  environment:
    - COUCHDB_USERNAME=alony
    - COUCHDB_PASSWORD=Passw00rd

app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8080:8080"
  volumes:
    - .:/root/HUBAPI
  command: bash -c "cd /root/HUBAPI swift build --clean && swift build --configuration release && .build/release/HUBServer"
  links:
    - db:localhost